### ISSUE TITLE
Unexpected token ")" when checking out the project 

### ISSUE THREAD

**Issue by linh-le** [gramps-graphql/data-source-base#23]
Hi everyone,

I'm playing around with GrAMPS, so trying the first 3 commands:
```
# 💥 zero dependencies! no global installs! create a new data source
npx graphql-cli create -b gramps-graphql/data-source-base data-source-mydata

# 📂 move into the newly-created data source
cd $_

# 🚀 start the GraphQL Playground with your spankin’ new data source
yarn dev
```
I got this issue when running the first command **npx graphql-cli create -b gramps-graphql/data-source-base data-source-mydata**
```
npx: installed 394 in 102.974s
<my-folder-info-deleted-for-privacy>\npm-cache\_npx\192\node_modules\graphql-cli\dist\bi
n.js
[graphql create] Downloading boilerplate from https://github.com/gramps-graphql/
data-source-base/archive/master.zip...
[graphql create] Installing node dependencies for <my-folder-info-deleted-for-privacy>\data-source-stitchingtest\package.json...
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.2: The platform "win32" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check.
Excluding it from installation.
[3/4] Linking dependencies...
warning "@gramps/cli > apollo-server-express > apollo-server-core > apollo-cache
-control@0.0.7" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0".
warning "@gramps/cli > apollo-server-express > apollo-server-core > apollo-traci
ng@0.1.1" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0".
warning "@gramps/cli > apollo-server-express > apollo-server-core > graphql-exte
nsions@0.0.5" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0".
warning " > babel-jest@22.0.4" has unmet peer dependency "babel-core@^6.0.0 || ^
7.0.0-0".
[4/4] Building fresh packages...
[-/2] ? waiting...
[2/2] ? weak: Building the projects in this solution one at a time. To
[-/2] ? waiting...
[-/2] ? waiting...
warning Error running install script for optional dependency: "<my-folder-info-deleted-for-privacy>\\data-source-stitchingtest\\node_modules\
\weak: Command failed.\nExit code: 1\nCommand: node-gyp rebuild\nArguments: \nDi
rectory:<my-folder-info-deleted-for-privacy>\\data-source-st
itchingtest\\node_modules\\weak\nOutput:\n<my-folder-info-deleted-for-privacy>\\data-source-stitchingtest\\node_modules\\weak>if not defined
npm_config_node_gyp (node \"C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\n
ode-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" rebuild )  els
e (node \"\" rebuild ) \r\ngyp info it worked if it ends with ok\ngyp info using
 node-gyp@3.4.0\ngyp info using node@6.10.3 | win32 | x64\ngyp info spawn C:\\Py
thon27\\python.exe\ngyp info spawn args [ 'C:\\\\Program Files\\\\nodejs\\\\node
_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\gyp\\\\gyp_main.py',\ngyp info sp
awn args   'binding.gyp',\ngyp info spawn args   '-f',\ngyp info spawn args   'm
svs',\ngyp info spawn args   '-G',\ngyp info spawn args   'msvs_version=auto',\n
gyp info spawn args   '-I',\ngyp info spawn args   <my-folder-info-deleted-for-privacy>\\\\data-source-stitchingtest\\\\node_modul
es\\\\weak\\\\build\\\\config.gypi',\ngyp info spawn args   '-I',\ngyp info spaw
n args   'C:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\
\\node-gyp\\\\addon.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   '
<my-folder-info-deleted-for-privacy>\\\\.node-gyp\\\\6.10.3\\\\include\\\\node\\\\common.gypi',\ng
yp info spawn args   '-Dlibrary=shared_library',\ngyp info spawn args   '-Dvisib
ility=default',\ngyp info spawn args   '-Dnode_root_dir=<my-folder-info-deleted-for-privacy>\\\\.n
ode-gyp\\\\6.10.3',\ngyp info spawn args   '-Dnode_gyp_dir=C:\\\\Program Files\\
\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp',\ngyp info spawn ar
gs   '-Dnode_lib_file=node.lib',\ngyp info spawn args   '-Dmodule_root_dir=<my-folder-info-deleted-for-privacy>\\\\data-source-stit
chingtest\\\\node_modules\\\\weak',\ngyp info spawn args   '--depth=.',\ngyp inf
o spawn args   '--no-parallel',\ngyp info spawn args   '--generator-output',\ngy
p info spawn args   '<my-folder-info-deleted-for-privacy>\\\\data-source-stitchingtest\\\\node_modules\\\\weak\\\\build',\ngyp info
 spawn args   '-Goutput_dir=.' ]\ngyp info spawn C:\\Windows\\Microsoft.NET\\Fra
mework\\v4.0.30319\\msbuild.exe\ngyp info spawn args [ 'build/binding.sln',\ngyp
 info spawn args   '/clp:Verbosity=minimal',\ngyp info spawn args   '/nologo',\n
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]\nBuilding the pr
ojects in this solution one at a time. To enable parallel build, please add the
\"/m\" switch.\r\nMSBUILD : error MSB3428: Could not load the Visual C++ compone
nt \"VCBuild.exe\". To fix this, 1) install the .NET Framework 2.0 SDK, 2) insta
ll Microsoft Visual Studio 2005 or 3) add the location of the component to the s
ystem path if it is installed elsewhere.  [<my-folder-info-deleted-for-privacy>\\data-source-stitchingtest\\node_modules\\weak\\build\\bindin
g.sln]\r\ngyp ERR! build error \ngyp ERR! stack Error: `C:\\Windows\\Microsoft.N
ET\\Framework\\v4.0.30319\\msbuild.exe` failed with exit code: 1\ngyp ERR! stack
     at ChildProcess.onExit (C:\\Program Files\\nodejs\\node_modules\\npm\\node_
modules\\node-gyp\\lib\\build.js:276:23)\ngyp ERR! stack     at emitTwo (events.
js:106:13)\ngyp ERR! stack     at ChildProcess.emit (events.js:191:7)\ngyp ERR!
stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:
12)\ngyp ERR! System Windows_NT 6.1.7601\ngyp ERR! command \"C:\\\\Program Files
\\\\nodejs\\\\node.exe\" \"C:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\
\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"rebuild\"\ngyp ERR! cwd C:
Done in 55.10s.
[graphql create] Running boilerplate install script...
x
Unexpected token )
```

It seems like there are multiple errors going on here (one with .NET framework, and the other with the unexpected token).
When I proceeded to run **yarn dev**, it throws the unexpected token again:
```
yarn run v1.3.2
$ gramps dev --data-source .
<my-folder-info-deleted-for-privacy>\data-source-stitchingtest\nod
e_modules\@gramps\cli\bin\dev.js:78
    )
    ^
SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.extWrap (<my-folder-info-deleted-for-privacy>\data-s
ource-stitchingtest\node_modules\reify\node\compile-hook.js:59:7)
    at Object.extManager (<my-folder-info-deleted-for-privacy>\dat
a-source-stitchingtest\node_modules\reify\node\compile-hook.js:19:12)
    at Object.manager [as .js] <my-folder-info-deleted-for-privacy>\data-source-stitchingtest\node_modules\reify\node\wrapper.js:108:20)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.
```
I looked at the file at node_modules\@gramps\cli\bin\dev.js:78. It doesn't seem like an unexpected token. Does anyone have any idea what might have caused this?

**Comment by linh-le** [comment]
Just figured it out. Updating to node 8.x and above fixes it.
